@controller=https://localhost:5001/api/Approval
//@controller=https://localhost:44326/api/approval
@authApproval1= bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMiLCJuYmYiOjE2MjQ4ODA5NTIsImV4cCI6MTYyNTQ4NTc1MiwiaWF0IjoxNjI0ODgwOTUyfQ.cguH1q9fFwd4D8lCIwvcKTIuzzKYcbGDTMN2Ipq5xTs
@authHSE=bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJuYmYiOjE2MjUxOTAxNzEsImV4cCI6MTYyNTc5NDk3MSwiaWF0IjoxNjI1MTkwMTcxfQ.K14E2yxHl2T83IObXsfn-Xq0pQDcnpky4JMb-ARVcIg
@authManager=bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJuYmYiOjE2MjUxOTAyMTcsImV4cCI6MTYyNTc5NTAxNywiaWF0IjoxNjI1MTkwMjE3fQ.3NTYvAz_k7GrPDZVQiej_HgnSX3f99OCBwnwzof-dpI




###

GET {{controller}}/GetPersetujuan HTTP/1.1
Content-Type: application/json
Authorization: {{authApproval1}}
####


####

POST {{controller}}/approve/1 HTTP/1.1
Content-Type: application/json
Authorization: {{authApproval1}}

[{"Id":0,"ItemPengajuanId":1,"ItemPemeriksaanId":1,"Hasil":true,"TindakLanjut":null,"Keterangan":null,"CompensationDeadline":null,"ItemPemeriksaan":{"Id":1,"Kelengkapan":"KEURDLLAJR","Penjelasan":"KEUR ","Pemeriksaan":null}},{"Id":0,"ItemPengajuanId":1,"ItemPemeriksaanId":2,"Hasil":true,"TindakLanjut":null,"Keterangan":null,"CompensationDeadline":null,"ItemPemeriksaan":{"Id":2,"Kelengkapan":"SIM","Penjelasan":"Surat Izin Mengemudi","Pemeriksaan":null}},{"Id":0,"ItemPengajuanId":1,"ItemPemeriksaanId":3,"Hasil":true,"TindakLanjut":null,"Keterangan":null,"CompensationDeadline":null,"ItemPemeriksaan":{"Id":3,"Kelengkapan":"STNK","Penjelasan":"Surat Tanda Nomor Kendaraan ","Pemeriksaan":null}},{"Id":0,"ItemPengajuanId":1,"ItemPemeriksaanId":4,"Hasil":true,"TindakLanjut":null,"Keterangan":null,"CompensationDeadline":null,"ItemPemeriksaan":{"Id":4,"Kelengkapan":"Kaca Spion","Penjelasan":"Kaca Spion Harus Lengkap","Pemeriksaan":null}}]
#####



GET {{controller}}/GetPenilaian/1 HTTP/1.1
Content-Type: application/json
Authorization: {{authApproval1}}