@controller=https://localhost:5001/api/companyadministrator
@auth= bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgiLCJuYmYiOjE2MDMxNzMwNDUsImV4cCI6MTYwMzc3Nzg0NSwiaWF0IjoxNjAzMTczMDQ1fQ.wLlKn5K4ZXlw2Cyi0AYp0okt5OtlEArftRxrp7L4n9U

POST {{controller}}/createprofile HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    "Name":"Pertamina A",
    "Address":"Kungkung",
    "Email" : "pertamina@gmail.com",
    "NPWP" : "Sony@77"
}

###
