//@controller=https://localhost:5001/api/itempemeriksaan

@controller=https://localhost:44326/api/itempemeriksaan
@auth= bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYmYiOjE2MjQyOTM0MTYsImV4cCI6MTYyNDg5ODIxNiwiaWF0IjoxNjI0MjkzNDE2fQ.5PlE7t2A3WLdMefav7SFquQ9dadu5B8DcZEEFa9TNoU



POST {{controller}} HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
    "Name":"Parent",
    "Items":[
        {
        "Kelengkapan":"Child 1",
        "Penjelasan":"Ini Child"
        },{
        "Kelengkapan":"Child 2",
        "Penjelasan":"Ini Child"
        }
    ]
}
####


PUT  {{controller}}?id=4 HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

  {
    "id": 4,
    "name": "Test A",
    "items": [
      {
        "kelengkapan": "Tes 1 Saja ",
        "penjelasan": "Ini adalah penjelasan test"
      },
      {
        "kelengkapan": "Tes 2 Saja ",
        "penjelasan": "Ini adalah penjelasan test"
      }
    ]
  }

####



GET  {{controller}} HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}




