@controller=http://localhost/api/users/authenticate

POST {{controller}} HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Administrator",
    "Password" : "Admin123"
}


###
//Company User
POST {{controller}} HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Ajn26",
    "Password" : "Sony@77"
}



###
//Approval1
POST {{controller}} HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Approval1",
    "Password" : "Sony@77"
}



###
//HSE
POST {{controller}} HTTP/1.1
Content-Type: application/json

{
    "UserName" : "HSE",
    "Password" : "Sony@77"
}




###
//Manager
POST {{controller}} HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Manager",
    "Password" : "Sony@77"
}

