//@controller=http://localhost/api/users
@controller=https://localhost:5001/api/users
//@controller=https://localhost:44326/api/users
//@controller=http://36.94.6.214/api/users

@auth= bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjciLCJuYmYiOjE2MjUwNDk4MzYsImV4cCI6MTYyNTY1NDYzNiwiaWF0IjoxNjI1MDQ5ODM2fQ.6mcxKM32TNgqEcN6lHgn6w3BEVKIAW3apuIBN2TVM6E
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Administrator",
    "Password" : "Admin123"
}


###
//Company User
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "minyakpapua",
    "Password" : "Sony@77"
}


###
//Company User
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "deni21",
    "Password" : "12345"
}

###
//Approval1
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Approval1",
    "Password" : "Approval123"
}

###
//HSE
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "HSE",
    "Password" : "Sony@77"
}

###
//Manager
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Manager",
    "Password" : "Sony@77"
}


###
//Manager
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Gate",
    "Password" : "Sony@77"
}


###
//Manager
GET  {{controller}} HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}



###