//@controller=http://localhost/api/users
//@controller=https://localhost:5001/api/users
//@controller=https://localhost:44326/api/users
@controller=https://kimprt.com/api/users

@auth= bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYmYiOjE2MzAzNzI4MDQsImV4cCI6MTYzMDk3NzYwNCwiaWF0IjoxNjMwMzcyODA0fQ.KUuqtkfAWKc393sisEUJFBMkzgg1peDEQ-jrmp7t8zc

POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Administrator",
    "Password" : "Admin123"
}


###
//Company User
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "minyakpapua",
    "Password" : "Sony@77"
}


###
//Company User
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "deni21",
    "Password" : "12345"
}

###
//Approval1
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Approval1",
    "Password" : "Sony@77"
}

###
//HSE
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "HSE",
    "Password" : "Sony@77"
}

###
//Manager
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Manager",
    "Password" : "Sony@77"
}


###
//Manager
POST {{controller}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "UserName" : "Gate",
    "Password" : "Sony@77"
}


###
//Manager
GET  {{controller}} HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}



###