name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore "WepApp.csproj"

    - name: Build app
      run: dotnet build "/CitraDigitalWebApp/WepApp/WepApp.csproj" -c Release --no-restore

    - name: Publish App
      run: dotnet publish "CitraDigitalWebApp/WepApp/WepApp.csproj" -c Release -o ./pertamina



    - name: Copy To VPS
      uses: appleboy/scp-action@master
      env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
      with:
          source: "./pupr"
          target: "/var/www"
          
    - name: cmod
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: chmod -R 777 /var/www/pertamina    

    - name: Run Kestrel Service
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: systemctl restart kestrel-pupr.service
